@extends('template.subPage')


@section('content')
		<div class="about-content">

			<h3>Speld nz Privacy Policy</h3>
			<p>By viewing and using this Site, you will be deemed to agree to this privacy statement. If you do not agree to this privacy statement, you should stop accessing and using the Site.</p>
			
			<h3>Cookies and Tracking</h3>
			<p>Speld nz uses a “cookie” file containing information that can track domain names, IP addresses, and browser types from people who visit our site. Speld nz may use the information generated by cookies to track traffic patterns to and from the Site and/or enable you to enter the Site and use certain services and to visit registered user only areas of the Site. You can choose to refuse cookies by turning them off in your browser and/or deleting them from your hard drive. You do not need to have cookies turned on to use the Site but you will need them to log on to the Site and to access personalised or secure content on the Site. Some pages may not function properly if the cookies are turned off.</p>
			<p>Where you provide personally identifiable information about yourself, we will use this information only to respond to your inquiry. We will not sell, rent or otherwise disclose that information (except as required by law) to third parties.</p>
						
			<h3>Links</h3>
			<p>Speld nz Web Site and News Letters contain links to other sites that may not follow the same privacy policies as Speld nz. We recommend that you check any relevant privacy policies before providing your personal information to any third party. Updates This privacy statement was last updated on 1st may, 2009. A notice will be posted on our Web site home page whenever this privacy statement is changed in a material way.</p>
						
			<h3>Updates</h3>
			<p>This privacy statement was last updated on 1 June, 2006. A notice will be posted on our Web site home page whenever this privacy statement is changed in a material way.</p>
		</div>
@stop		